FROM openjdk
WORKDIR usr/lib
ADD ./target/E-Commerce-Furniture-Application-0.0.1-SNAPSHOT.jar /usr/lib/E-Commerce-Furniture-Application-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","E-Commerce-Furniture-Application-0.0.1-SNAPSHOT.jar"]
